function typeAt(view,offset){return String.fromCharCode(view.getUint8(offset),view.getUint8(offset+1),view.getUint8(offset+2),view.getUint8(offset+3))}
function readBox(view,offset,limit){if(offset+8>limit)return null;let size=view.getUint32(offset),type=typeAt(view,offset+4),header=8;if(size===1){if(offset+16>limit)return null;const big=view.getBigUint64(offset+8);if(big>BigInt(Number.MAX_SAFE_INTEGER))throw new Error(`MP4 box ${type} is too large`);size=Number(big);header=16}else if(size===0)size=limit-offset;if(size<header||offset+size>limit)throw new Error(`Invalid MP4 box ${type}`);return{type,start:offset,size,header,dataStart:offset+header,end:offset+size}}
function children(view,start,end){const out=[];let p=start;while(p+8<=end){const b=readBox(view,p,end);if(!b)break;out.push(b);p=b.end}return out}
function child(view,parent,type){return children(view,parent.dataStart,parent.end).find(b=>b.type===type)||null}const fullBoxPayload=box=>box.dataStart+4;
function parseMdhd(view,box){const version=view.getUint8(box.dataStart);let p=fullBoxPayload(box);if(version===1){p+=16;const timescale=view.getUint32(p);p+=4;return{timescale,duration:Number(view.getBigUint64(p))}}p+=8;const timescale=view.getUint32(p);p+=4;return{timescale,duration:view.getUint32(p)}}
function parseHdlr(view,box){return typeAt(view,fullBoxPayload(box)+4)}
function parseStts(view,box){let p=fullBoxPayload(box),n=view.getUint32(p);p+=4;const e=[];for(let i=0;i<n;i++){e.push({count:view.getUint32(p),delta:view.getUint32(p+4)});p+=8}return e}
function parseCtts(view,box){const version=view.getUint8(box.dataStart);let p=fullBoxPayload(box),n=view.getUint32(p);p+=4;const e=[];for(let i=0;i<n;i++){e.push({count:view.getUint32(p),offset:version===1?view.getInt32(p+4):view.getUint32(p+4)});p+=8}return e}
function parseStsc(view,box){let p=fullBoxPayload(box),n=view.getUint32(p);p+=4;const e=[];for(let i=0;i<n;i++){e.push({firstChunk:view.getUint32(p),samplesPerChunk:view.getUint32(p+4),sampleDescriptionIndex:view.getUint32(p+8)});p+=12}return e}
function parseStsz(view,box){let p=fullBoxPayload(box),sampleSize=view.getUint32(p),count=view.getUint32(p+4);p+=8;if(sampleSize)return new Array(count).fill(sampleSize);const s=new Array(count);for(let i=0;i<count;i++){s[i]=view.getUint32(p);p+=4}return s}
function parseChunkOffsets(view,box){let p=fullBoxPayload(box),n=view.getUint32(p);p+=4;const o=[];if(box.type==='stco')for(let i=0;i<n;i++){o.push(view.getUint32(p));p+=4}else for(let i=0;i<n;i++){const v=view.getBigUint64(p);if(v>BigInt(Number.MAX_SAFE_INTEGER))throw new Error('MP4 chunk offset too large');o.push(Number(v));p+=8}return o}
function parseStss(view,box){if(!box)return null;let p=fullBoxPayload(box),n=view.getUint32(p);p+=4;const s=new Set;for(let i=0;i<n;i++){s.add(view.getUint32(p)-1);p+=4}return s}
function parseStsd(view,box){let p=fullBoxPayload(box),n=view.getUint32(p);p+=4;for(let i=0;i<n;i++){const entry=readBox(view,p,box.end);if(!entry)break;if(entry.type==='avc1'||entry.type==='avc3'){const width=view.getUint16(entry.start+32),height=view.getUint16(entry.start+34);let avcC=null;for(const b of children(view,entry.start+86,entry.end))if(b.type==='avcC'){avcC=b;break}if(!avcC)throw new Error('MP4 AVC track has no avcC box');const description=new Uint8Array(view.buffer.slice(avcC.dataStart,avcC.end));const hex=v=>v.toString(16).padStart(2,'0').toUpperCase(),codec=`${entry.type}.${hex(description[1])}${hex(description[2])}${hex(description[3])}`;return{codec,width,height,description}}p=entry.end}throw new Error('No H.264/AVC video sample entry found')}
function expandTiming(stts,count){const dts=new Array(count),durations=new Array(count);let t=0,i=0;for(const e of stts)for(let k=0;k<e.count&&i<count;k++,i++){dts[i]=t;durations[i]=e.delta;t+=e.delta}if(i!==count)throw new Error('stts sample count mismatch');return{dts,durations,total:t}}
function expandOffsets(ctts,count){const out=new Array(count).fill(0);if(!ctts)return out;let i=0;for(const e of ctts)for(let k=0;k<e.count&&i<count;k++,i++)out[i]=e.offset;if(i!==count)throw new Error('ctts sample count mismatch');return out}
function buildSampleOffsets(sizes,chunks,stsc){const out=new Array(sizes.length);let sample=0,ei=0;for(let chunk=1;chunk<=chunks.length;chunk++){while(ei+1<stsc.length&&chunk>=stsc[ei+1].firstChunk)ei++;let off=chunks[chunk-1];for(let j=0;j<stsc[ei].samplesPerChunk&&sample<sizes.length;j++,sample++){out[sample]=off;off+=sizes[sample]}}if(sample!==sizes.length)throw new Error('stsc/chunk sample count mismatch');return out}
export function parseMp4(arrayBuffer){const view=new DataView(arrayBuffer),moov=children(view,0,view.byteLength).find(b=>b.type==='moov');if(!moov)throw new Error('MP4 moov box not found');let video=null;for(const trak of children(view,moov.dataStart,moov.end).filter(b=>b.type==='trak')){const mdia=child(view,trak,'mdia');if(!mdia)continue;const hdlr=child(view,mdia,'hdlr');if(!hdlr||parseHdlr(view,hdlr)!=='vide')continue;const mdhd=child(view,mdia,'mdhd'),minf=child(view,mdia,'minf'),stbl=minf&&child(view,minf,'stbl');if(!mdhd||!stbl)continue;const stsd=child(view,stbl,'stsd'),sttsBox=child(view,stbl,'stts'),stscBox=child(view,stbl,'stsc'),stszBox=child(view,stbl,'stsz'),stcoBox=child(view,stbl,'stco')||child(view,stbl,'co64');if(!stsd||!sttsBox||!stscBox||!stszBox||!stcoBox)throw new Error('MP4 video sample table is incomplete');const media=parseMdhd(view,mdhd),sampleEntry=parseStsd(view,stsd),sizes=parseStsz(view,stszBox),stts=parseStts(view,sttsBox),cttsBox=child(view,stbl,'ctts'),ctts=cttsBox?parseCtts(view,cttsBox):null,stsc=parseStsc(view,stscBox),chunks=parseChunkOffsets(view,stcoBox),sync=parseStss(view,child(view,stbl,'stss')),offsets=buildSampleOffsets(sizes,chunks,stsc),timing=expandTiming(stts,sizes.length),comp=expandOffsets(ctts,sizes.length),samples=sizes.map((size,i)=>({index:i,offset:offsets[i],size,dts:timing.dts[i],pts:timing.dts[i]+comp[i],duration:timing.durations[i],key:sync?sync.has(i):true}));video={...sampleEntry,timescale:media.timescale,durationTicks:timing.total,duration:timing.total/media.timescale,fps:sizes.length/(timing.total/media.timescale),samples};break}if(!video)throw new Error('No video track found in MP4');return{buffer:arrayBuffer,...video}}
function nearestKey(samples,index){let i=Math.min(Math.max(0,index),samples.length-1);while(i>0&&!samples[i].key)i--;return i}
export async function decodeFrames(mp4,onFrame,options={}){if(!('VideoDecoder'in globalThis))throw new Error('このブラウザはWebCodecs VideoDecoderに対応していません。Chrome/Edge最新版を使用してください。');const startTime=options.startTime??0,endTime=options.endTime??Infinity;let desired=mp4.samples.findIndex(s=>s.pts/mp4.timescale>=startTime-1e-9);if(desired<0)desired=mp4.samples.length-1;const feedStart=nearestKey(mp4.samples,desired);let feedEnd=mp4.samples.findIndex(s=>s.pts/mp4.timescale>endTime+1e-9);if(feedEnd<0)feedEnd=mp4.samples.length;else feedEnd=Math.min(mp4.samples.length,feedEnd+1);const ptsToIndex=new Map;for(let i=feedStart;i<feedEnd;i++)ptsToIndex.set(Math.round(mp4.samples[i].pts/mp4.timescale*1e6),i);let outputError=null;const decoder=new VideoDecoder({output:frame=>{try{const ts=Number(frame.timestamp);let index=ptsToIndex.get(ts);if(index==null){let best=feedStart,bestD=Infinity;for(let i=feedStart;i<feedEnd;i++){const d=Math.abs(Math.round(mp4.samples[i].pts/mp4.timescale*1e6)-ts);if(d<bestD){bestD=d;best=i}}index=best}const nominalTime=index/mp4.fps;if(nominalTime+1/mp4.fps>=startTime&&nominalTime<=endTime+1/mp4.fps)onFrame(frame,{index,nominalTime,ptsTime:ts/1e6})}catch(e){outputError=e}finally{frame.close()}},error:e=>{outputError=e}});decoder.configure({codec:mp4.codec,codedWidth:mp4.width,codedHeight:mp4.height,description:mp4.description,optimizeForLatency:false});const bytes=new Uint8Array(mp4.buffer);for(let i=feedStart;i<feedEnd;i++){if(outputError)break;while(decoder.decodeQueueSize>16)await new Promise(r=>setTimeout(r,0));const s=mp4.samples[i];decoder.decode(new EncodedVideoChunk({type:s.key?'key':'delta',timestamp:Math.round(s.pts/mp4.timescale*1e6),duration:Math.max(1,Math.round(s.duration/mp4.timescale*1e6)),data:bytes.subarray(s.offset,s.offset+s.size)}))}await decoder.flush();decoder.close();if(outputError)throw outputError}
