const utf8=new TextDecoder('utf-8');
function crcTable(){const t=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?(0xEDB88320^(c>>>1)):(c>>>1);t[n]=c>>>0;}return t;}const CRC_TABLE=crcTable();
export function crc32(bytes,end=bytes.length){let c=0xFFFFFFFF;for(let i=0;i<end;i++)c=CRC_TABLE[(c^bytes[i])&0xFF]^(c>>>8);return(c^0xFFFFFFFF)>>>0;}
function parseHeader(view){let magic='';for(let i=0;i<8;i++){const c=view.getUint8(i);if(c)magic+=String.fromCharCode(c);}const h={magic,format_version:view.getUint16(8,true),header_size:view.getUint16(10,true),run_id:view.getUint32(12,true),run_start_us:Number(view.getBigUint64(16,true)),metadata_json_size:view.getUint32(24,true),sample_count:view.getUint32(28,true),summary_count:view.getUint32(32,true),event_count:view.getUint32(36,true),log_sample_size:view.getUint16(40,true),summary_row_size:view.getUint16(42,true),event_row_size:view.getUint16(44,true),log_period_ms:view.getUint16(46,true),imu_period_ms:view.getUint16(48,true),roller_read_period_ms:view.getUint16(50,true),web_update_period_ms:view.getUint16(52,true),total_trials:view.getUint16(54,true),preset_id:view.getUint16(56,true),flags:view.getUint32(58,true),samples_offset:view.getUint32(62,true),summaries_offset:view.getUint32(66,true),events_offset:view.getUint32(70,true),crc_offset:view.getUint32(74,true)};if(h.magic!=='RWLOG01')throw new Error(`RWLOG magicが不正です: ${h.magic}`);if(h.header_size!==110)throw new Error(`未対応のRWLOG header size: ${h.header_size}`);if(h.format_version!==34&&h.format_version!==35)throw new Error(`Web版は現在RWLOG v34/v35に対応しています (入力 v${h.format_version})`);const expected=h.format_version===35?146:138;if(h.log_sample_size!==expected)throw new Error(`RWLOG sample sizeが想定と異なります: ${h.log_sample_size} != ${expected}`);return h;}
function readPrimitive(view,pos,type){switch(type){case'I':return[view.getUint32(pos,true),pos+4];case'H':return[view.getUint16(pos,true),pos+2];case'B':return[view.getUint8(pos),pos+1];case'b':return[view.getInt8(pos),pos+1];case'h':return[view.getInt16(pos,true),pos+2];default:throw new Error(type);}}
const PREFIX=['I','I','B','I','B','b','h','h','H','H','B','B','I','I','h','H','H','h','H','H','h','h','B'];
function readSampleValues(view,offset,version){const types=[...PREFIX,...new Array(version===35?41:37).fill('h'),'H','B','B','B','B','h','h','h','h'],values=[];let p=offset;for(const t of types){let v;[v,p]=readPrimitive(view,p,t);values.push(v);}return values;}
const deg=v=>v/100.0;
function convert34(v){const row={t_test_ms:v[1],state_id:v[2],sync_event_id:v[62],led_state:v[61],log_active:v[63]};row.pitch_madgwick_beta1_raw_deg=deg(v[28]);row.pitch_madgwick_beta1_bias_deg=deg(v[29]);['pitch_fixed_b100_deg','pitch_fixed_b000_deg','pitch_dynamic_hold073_deg','pitch_dynamic_hold120_deg','pitch_dynamic_hold170_deg'].forEach((n,i)=>row[n]=deg(v[30+i]));row.pitch_gyro_raw_deg=deg(v[35]);row.pitch_gyro_bias_corrected_deg=deg(v[36]);row.pitch_accel_only_deg=deg(v[37]);return row;}
function convert35(v){const row={t_test_ms:v[1],state_id:v[2],sync_event_id:v[66],led_state:v[65],log_active:v[67]};row.pitch_madgwick_beta1_raw_deg=deg(v[29]);row.pitch_madgwick_beta1_bias_deg=deg(v[30]);['pitch_fixed_b100_deg','pitch_fixed_b000_deg','pitch_dynamic_hold073_deg','pitch_dynamic_hold120_deg','pitch_dynamic_hold170_deg','pitch_dynamic_turnfast_deg'].forEach((n,i)=>row[n]=deg(v[31+i]));row.pitch_gyro_raw_deg=deg(v[37]);row.pitch_gyro_bias_corrected_deg=deg(v[38]);row.pitch_accel_only_deg=deg(v[39]);return row;}
export function parseRwlog(arrayBuffer){const view=new DataView(arrayBuffer),bytes=new Uint8Array(arrayBuffer),header=parseHeader(view);if(header.crc_offset+4>bytes.length)throw new Error('RWLOGがCRCより前で途切れています');const stored=view.getUint32(header.crc_offset,true),computed=crc32(bytes,header.crc_offset),crcOk=stored===computed,metaStart=header.header_size,metaEnd=metaStart+header.metadata_json_size;let metadata={};try{metadata=JSON.parse(utf8.decode(bytes.subarray(metaStart,metaEnd)));}catch(e){metadata={parse_error:String(e)};}const rows=new Array(header.sample_count);for(let i=0;i<header.sample_count;i++){const off=header.samples_offset+i*header.log_sample_size;if(off+header.log_sample_size>bytes.length)throw new Error(`RWLOG sample ${i} がファイル範囲外です`);const values=readSampleValues(view,off,header.format_version);rows[i]=header.format_version===35?convert35(values):convert34(values);}return{header,metadata,rows,crcOk,storedCrc:stored,computedCrc:computed};}
export function measurementRows(rows){let selected=rows.filter(r=>r.t_test_ms>=0&&r.state_id===3);if(selected.length>=20)return selected;selected=rows.filter(r=>r.t_test_ms>=0);if(selected.length<20)throw new Error('RWLOGの測定サンプルが少なすぎます');return selected;}
export function extractRwlogAnchors(rows){let start=null,end=null,previous=-1;const mids=[];for(const r of rows){const t=r.t_test_ms/1000,id=r.sync_event_id;if(id===2&&start==null)start=t;if(id===5&&previous!==5)mids.push(t);if(id===4&&end==null)end=t;previous=id;}if(start==null)throw new Error('RWLOGの sync_event_id=2 (t=0) が見つかりません');if(end==null)throw new Error('RWLOGの sync_event_id=4 (END) が見つかりません');if(mids.length!==6)throw new Error(`RWLOGのMID同期は6個必要です (検出 ${mids.length})`);const a=[start,...mids,end];for(let i=1;i<a.length;i++)if(a[i]<=a[i-1])throw new Error('RWLOG同期時刻が単調増加ではありません');return a;}
export function t0Reference(rows,column){const row=rows.find(r=>r.sync_event_id===2&&Number.isFinite(r[column]));if(!row)throw new Error(`${column} のt=0基準値がありません`);return row[column];}
export function pitchColumns(rows){if(!rows.length)return[];const keys=Object.keys(rows[0]).filter(k=>k.startsWith('pitch_')&&k.endsWith('_deg'));return keys.filter(k=>rows.reduce((n,r)=>n+(Number.isFinite(r[k])?1:0),0)>=20);}
