const utf8=new TextDecoder('utf-8');
function crcTable(){const t=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?(0xEDB88320^(c>>>1)):(c>>>1);t[n]=c>>>0;}return t;}const CRC_TABLE=crcTable();
export function crc32(bytes,end=bytes.length){let c=0xFFFFFFFF;for(let i=0;i<end;i++)c=CRC_TABLE[(c^bytes[i])&0xFF]^(c>>>8);return(c^0xFFFFFFFF)>>>0;}
function parseHeader(view){let magic='';for(let i=0;i<8;i++){const c=view.getUint8(i);if(c)magic+=String.fromCharCode(c);}const h={magic,format_version:view.getUint16(8,true),header_size:view.getUint16(10,true),run_id:view.getUint32(12,true),run_start_us:Number(view.getBigUint64(16,true)),metadata_json_size:view.getUint32(24,true),sample_count:view.getUint32(28,true),summary_count:view.getUint32(32,true),event_count:view.getUint32(36,true),log_sample_size:view.getUint16(40,true),summary_row_size:view.getUint16(42,true),event_row_size:view.getUint16(44,true),log_period_ms:view.getUint16(46,true),imu_period_ms:view.getUint16(48,true),roller_read_period_ms:view.getUint16(50,true),web_update_period_ms:view.getUint16(52,true),total_trials:view.getUint16(54,true),preset_id:view.getUint16(56,true),flags:view.getUint32(58,true),samples_offset:view.getUint32(62,true),summaries_offset:view.getUint32(66,true),events_offset:view.getUint32(70,true),crc_offset:view.getUint32(74,true)};if(h.magic!=='RWLOG01')throw new Error(`RWLOG magicが不正です: ${h.magic}`);if(h.header_size!==110)throw new Error(`未対応のRWLOG header size: ${h.header_size}`);if(h.format_version!==34&&h.format_version!==35)throw new Error(`Web版は現在RWLOG v34/v35に対応しています (入力 v${h.format_version})`);const expected=h.format_version===35?146:138;if(h.log_sample_size!==expected)throw new Error(`RWLOG sample sizeが想定と異なります: ${h.log_sample_size} != ${expected}`);return h;}
function readPrimitive(view,pos,type){switch(type){case'I':return[view.getUint32(pos,true),pos+4];case'H':return[view.getUint16(pos,true),pos+2];case'B':return[view.getUint8(pos),pos+1];case'b':return[view.getInt8(pos),pos+1];case'h':return[view.getInt16(pos,true),pos+2];default:throw new Error(type);}}
const PREFIX=['I','I','B','I','B','b','h','h','H','H','B','B','I','I','h','H','H','h','H','H','h','h','B'];
function readSampleValues(view,offset,version){const types=[...PREFIX,...new Array(version===35?41:37).fill('h'),'H','B','B','B','B','h','h','h','h'],values=[];let p=offset;for(const t of types){let v;[v,p]=readPrimitive(view,p,t);values.push(v);}return values;}
const deg=v=>v/100.0,beta=v=>v/10000.0;
function common(v){return{log_time_s:v[0]/1e6,t_test_ms:v[1],state_id:v[2],pulse_id:v[3],pulse_active:v[4],pulse_direction:v[5],motor_cmd_mA:v[6],current_mA_setting:v[7],pulse_width_ms_setting:v[8],input_interval_ms:v[9],trial_index:v[10],trial_count:v[11],trial_elapsed_ms:v[12],trial_duration_ms:v[13],trial_current_mA:v[14],trial_pulse_width_ms:v[15],trial_input_interval_ms:v[16],trial_predicted_beta_min:beta(v[17]),beta_recovery_tau_s:v[18]/1000,beta_model_vbat_mV:v[19],predicted_i_goal_mA:v[20],predicted_peak_current_mA:v[21],beta_model_vbat_status:v[22]};}
function assign(row,v,start,names,convert=x=>x){for(let i=0;i<names.length;i++)row[names[i]]=convert(v[start+i]);}
function convert34(v){const row=common(v);assign(row,v,23,['beta_ceiling_fixed_b100','beta_ceiling_fixed_b000','beta_ceiling_dynamic_hold073','beta_ceiling_dynamic_hold120','beta_ceiling_dynamic_hold170'],beta);row.pitch_madgwick_beta1_raw_deg=deg(v[28]);row.pitch_madgwick_beta1_bias_deg=deg(v[29]);assign(row,v,30,['pitch_fixed_b100_deg','pitch_fixed_b000_deg','pitch_dynamic_hold073_deg','pitch_dynamic_hold120_deg','pitch_dynamic_hold170_deg'],deg);row.pitch_gyro_raw_deg=deg(v[35]);row.pitch_gyro_bias_corrected_deg=deg(v[36]);row.pitch_accel_only_deg=deg(v[37]);row.gyro_bias_x_dps=deg(v[38]);row.gyro_bias_y_dps=deg(v[39]);row.gyro_bias_z_dps=deg(v[40]);row.gyro_pitch_rate_dps=deg(v[41]);assign(row,v,42,['beta_target_fixed_b100','beta_target_fixed_b000','beta_target_dynamic_hold073','beta_target_dynamic_hold120','beta_target_dynamic_hold170'],beta);assign(row,v,47,['beta_applied_fixed_b100','beta_applied_fixed_b000','beta_applied_dynamic_hold073','beta_applied_dynamic_hold120','beta_applied_dynamic_hold170'],beta);row.ax_g=v[52]/1000;row.ay_g=v[53]/1000;row.az_g=v[54]/1000;row.gx_dps=v[55]/100;row.gy_dps=v[56]/100;row.gz_dps=v[57]/100;row.acc_norm_g=v[58]/1000;row.roller_actual_current_mA=v[59];row.roller_battery_mV=v[60];row.led_state=v[61];row.sync_event_id=v[62];row.log_active=v[63];row.beta_phase_state=v[64];row.beta_phase_progress=beta(v[65]);row.beta_phase_peak_angle_deg=deg(v[66]);row.beta_phase_angle_deg=deg(v[67]);row.beta_phase_ceiling=beta(v[68]);return row;}
function convert35(v){const row=common(v);assign(row,v,23,['beta_ceiling_fixed_b100','beta_ceiling_fixed_b000','beta_ceiling_dynamic_hold073','beta_ceiling_dynamic_hold120','beta_ceiling_dynamic_hold170','beta_ceiling_dynamic_turnfast'],beta);row.pitch_madgwick_beta1_raw_deg=deg(v[29]);row.pitch_madgwick_beta1_bias_deg=deg(v[30]);assign(row,v,31,['pitch_fixed_b100_deg','pitch_fixed_b000_deg','pitch_dynamic_hold073_deg','pitch_dynamic_hold120_deg','pitch_dynamic_hold170_deg','pitch_dynamic_turnfast_deg'],deg);row.pitch_gyro_raw_deg=deg(v[37]);row.pitch_gyro_bias_corrected_deg=deg(v[38]);row.pitch_accel_only_deg=deg(v[39]);row.gyro_bias_x_dps=deg(v[40]);row.gyro_bias_y_dps=deg(v[41]);row.gyro_bias_z_dps=deg(v[42]);row.gyro_pitch_rate_dps=deg(v[43]);assign(row,v,44,['beta_target_fixed_b100','beta_target_fixed_b000','beta_target_dynamic_hold073','beta_target_dynamic_hold120','beta_target_dynamic_hold170','beta_target_dynamic_turnfast'],beta);assign(row,v,50,['beta_applied_fixed_b100','beta_applied_fixed_b000','beta_applied_dynamic_hold073','beta_applied_dynamic_hold120','beta_applied_dynamic_hold170','beta_applied_dynamic_turnfast'],beta);row.ax_g=v[56]/1000;row.ay_g=v[57]/1000;row.az_g=v[58]/1000;row.gx_dps=v[59]/100;row.gy_dps=v[60]/100;row.gz_dps=v[61]/100;row.acc_norm_g=v[62]/1000;row.roller_actual_current_mA=v[63];row.roller_battery_mV=v[64];row.led_state=v[65];row.sync_event_id=v[66];row.log_active=v[67];row.turn_fast_state=v[68];row.turn_fast_recovery_progress=beta(v[69]);row.turn_fast_peak_angle_deg=deg(v[70]);row.turn_fast_integrated_angle_deg=deg(v[71]);row.turn_fast_beta_target=beta(v[72]);return row;}
export function parseRwlog(arrayBuffer){const view=new DataView(arrayBuffer),bytes=new Uint8Array(arrayBuffer),header=parseHeader(view);if(header.crc_offset+4>bytes.length)throw new Error('RWLOGがCRCより前で途切れています');const stored=view.getUint32(header.crc_offset,true),computed=crc32(bytes,header.crc_offset),crcOk=stored===computed,metaStart=header.header_size,metaEnd=metaStart+header.metadata_json_size;let metadata={};try{metadata=JSON.parse(utf8.decode(bytes.subarray(metaStart,metaEnd)));}catch(e){metadata={parse_error:String(e)};}const rows=new Array(header.sample_count);for(let i=0;i<header.sample_count;i++){const off=header.samples_offset+i*header.log_sample_size;if(off+header.log_sample_size>bytes.length)throw new Error(`RWLOG sample ${i} がファイル範囲外です`);const values=readSampleValues(view,off,header.format_version);rows[i]=header.format_version===35?convert35(values):convert34(values);}return{header,metadata,rows,crcOk,storedCrc:stored,computedCrc:computed};}
export function measurementRows(rows){let selected=rows.filter(r=>r.t_test_ms>=0&&r.state_id===3);if(selected.length>=20)return selected;selected=rows.filter(r=>r.t_test_ms>=0);if(selected.length<20)throw new Error('RWLOGの測定サンプルが少なすぎます');return selected;}
export function extractRwlogAnchors(rows){let start=null,end=null,previous=-1;const mids=[];for(const r of rows){const t=r.t_test_ms/1000,id=r.sync_event_id;if(id===2&&start==null)start=t;if(id===5&&previous!==5)mids.push(t);if(id===4&&end==null)end=t;previous=id;}if(start==null)throw new Error('RWLOGの sync_event_id=2 (t=0) が見つかりません');if(end==null)throw new Error('RWLOGの sync_event_id=4 (END) が見つかりません');if(mids.length!==6)throw new Error(`RWLOGのMID同期は6個必要です (検出 ${mids.length})`);const a=[start,...mids,end];for(let i=1;i<a.length;i++)if(a[i]<=a[i-1])throw new Error('RWLOG同期時刻が単調増加ではありません');return a;}
export function t0Reference(rows,column){const row=rows.find(r=>r.sync_event_id===2&&Number.isFinite(r[column]));if(!row)throw new Error(`${column} のt=0基準値がありません`);return row[column];}
export function pitchColumns(rows){if(!rows.length)return[];const keys=Object.keys(rows[0]).filter(k=>k.startsWith('pitch_')&&k.endsWith('_deg'));return keys.filter(k=>rows.reduce((n,r)=>n+(Number.isFinite(r[k])?1:0),0)>=20);}
export function numericColumns(rows,minFinite=20){if(!rows.length)return[];const keys=new Set();for(const r of rows)for(const[k,v]of Object.entries(r))if(Number.isFinite(v))keys.add(k);return[...keys].filter(k=>rows.reduce((n,r)=>n+(Number.isFinite(r[k])?1:0),0)>=minFinite);}
